puts "-------*------------*----------*---------The matrix menu----------*-----------*-------------*-----"
puts "--------------------------------------------------------------------------------------------------"
puts "I M N - Create a new M x N image with all pixels coloured white (O)."
puts "C - Clears the table, setting all pixels to white (O)."
puts "L X Y C - Colours the pixel (X,Y) with colour C."
puts "V X Y1 Y2 C - Draw a vertical segment of colour C in column X between rows Y1 and Y2 (inclusive)."
puts "H X1 X2 Y C - Draw a horizontal segment of colour C in row Y between columns X1 and X2 (inclusive)."
puts "S - Show the contents of the current image"
puts "X - Terminate the session"
puts "-------*------------*----------*---------*------------*-----------*-----------*-------------*-----"